kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: gitflow
  name: gitflow-manager-role
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] # You can also use ["*"]
